# Generated by Django 3.2.7 on 2022-01-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='train_details',
            fields=[
                ('train_id', models.IntegerField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=100)),
                ('train_class', models.CharField(max_length=10)),
                ('seat_status', models.CharField(blank=True, max_length=15, null=True)),
                ('available_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('start_dest', models.CharField(max_length=100)),
                ('end_dest', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'train_details',
            },
        ),
    ]
