# Generated by Django 3.2.7 on 2022-01-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_details',
            name='available_date',
            field=models.DateTimeField(),
        ),
    ]
